services:
  couchbase:
    image: deminy/couchbase
    environment:
      CB_ADMIN: username
      CB_ADMIN_PASSWORD: password
      CB_CLUSTER_RAM_SIZE: 300 # Note that RAM quota for each bucket in Couchbase cannot be less than 100 MiB.
      CB_BUCKETS: test1,test2,test3
      CB_SERVICES: data,index,query,fts
    ports:
      - 8091
