name: Build and Publish Versioned Couchbase Image

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - '[4-9].[0-9]+.[0-9]+-?[a-zA-Z]**'
  workflow_dispatch:

jobs:
  build-and-publish-versioned:
    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set output parameters
        id: params
        run: |
          set -ex

          branch_name=${GITHUB_REF##*/}
          major_version=${branch_name%.*}

          echo "::set-output name=branch_name::${branch_name}"
          if [[ ${major_version} =~ ^7\.[1-9] ]] ; then
            echo "::set-output name=docker_file::dockerfiles/${major_version}.x/Dockerfile"
            echo "::set-output name=platforms::linux/amd64,linux/arm64/v8"
          else
            echo "::set-output name=docker_file::dockerfiles/${branch_name}/Dockerfile"
            echo "::set-output name=platforms::linux/amd64"
          fi

      -
        name: Build and Publish Versioned Couchbase Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ steps.params.outputs.docker_file }}
          build-args: |
            COUCHBASE_VERSION=${{ steps.params.outputs.branch_name }}
          platforms: ${{ steps.params.outputs.platforms }}
          push: true
          tags: deminy/couchbase:${{ steps.params.outputs.branch_name }}

      -
        name: Image Digest of deminy/couchbase:${{ steps.params.outputs.branch_name }}
        run: echo ${{ steps.docker_build.outputs.digest }}
