name: Build and Publish Latest Couchbase Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build and Publish Latest Couchbase Image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: couchbase
