name: Build and Publish Latest Couchbase Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Latest Couchbase Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/latest/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: deminy/couchbase:latest

      -
        name: Image Digest of deminy/couchbase:latest
        run: echo ${{ steps.docker_build.outputs.digest }}
