name: Build and Publish Versioned Couchbase Image

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - '[4-9].[0-9]+.[0-9]+-?[a-zA-Z]**'
  workflow_dispatch:

jobs:
  build-and-publish-versioned:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Versioned Couchbase Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: deminy/couchbase:${GITHUB_REF##*/}

      -
        name: Image Digest of deminy/couchbase:${GITHUB_REF##*/}
        run: echo ${{ steps.docker_build.outputs.digest }}
